### ISSUE TITLE
Update to requests-oauthlib 2.0.0

### ISSUE THREAD

**Issue by z1lc** [sns-sdks/python-youtube#173]
https://pypi.org/project/requests-oauthlib/ recently updated to 2.0.0. The poetry specification requires <2.0.0:

https://github.com/sns-sdks/python-youtube/blob/45b0b2284d9b4ab8c41529366dcfec03492f39ba/pyproject.toml#L35

**Comment by z1lc** [comment]
@MerleLiuKun / @pidi3000 any thoughts here? I can't upgrade the version of this library in my own project since `pip` complains that python-youtube limits the max version.

This also is now also affecting `isodate`, since 0.7.2 was recently released:
https://github.com/sns-sdks/python-youtube/blob/45b0b2284d9b4ab8c41529366dcfec03492f39ba/pyproject.toml#L36

**Comment by MerleLiuKun** [comment]
I will take care of this issue this week. :)

**Comment by pidi3000** [comment]
I see no issue updating `requests-oauthlib`.
I'd suggest setting it to something like `requests-oauthlib = ">=1.3.0,<3.0.0"`.

This way all of v2 is included. Since they seem to have started following semantic versioning this should not cause problems and version 3 might add breaking changes.

#
Updating `isodate` to the newest version of `0.7.2` will also require increasing `python-youtube's` minimum python version from `3.6` to `3.7`.
Probably best to pin to `0.7.2` or limiting it to be no higher to avoid problems. 
Since `0.7.3` seems to plan dropping support for python versions below `3.9`.
([isodate changes](https://github.com/gweis/isodate/blob/master/CHANGES.txt))

I propose setting it to `isodate = ">=0.6.0,<=0.7.2"` for now

**Comment by pidi3000** [comment]
with #184 merged I think this can be closed
