### ISSUE TITLE
Can't get channel info by name

### ISSUE THREAD

**Issue by YandereKat** [sns-sdks/python-youtube#86]
Hello, I'm trying the library out and I can't get any channel info by name. I noticed that only the channels with "user" in their link (https://www.youtube.com/user/GoogleDevelopers) work properly using it. Channels with links like: (https://www.youtube.com/channel/ChannelID), (https://www.youtube.com/c/ChannelName) return None.

Any help appreciated!

**Comment by YandereKat** [comment]
Just wanted to add - I'm creating a discord bot, so I would like members to be able to search for channels by their channel name that is being displayed.

**Comment by MerleLiuKun** [comment]
The link https://www.youtube.com/c/ChannelName is the custom url. Not the username, So you can not get channel data.

As for me, Maybe you can use the search api to get data. you can try it.

**Comment by mhoonjeon** [comment]
Same problem here.

**Comment by MerleLiuKun** [comment]
Ok, there have some misinformation,

`channel_name` parameter for api `get_channel_info` means: The forUsername parameter specifies a YouTube username, thereby requesting the channel associated with that username.

- https://www.youtube.com/c/customurl:  `ChannelName` is a custom url set by the channel owner.  more docs for [customUrl](https://developers.google.com/youtube/v3/docs/channels#snippet.customUrl)

- Channel title: 
![channel title](https://user-images.githubusercontent.com/28470060/115362958-9e9b4480-a1f4-11eb-9edd-b6d361bc7a09.png)

But those not the parameter mean.

I think this because the parameter name is not correct.  I will change it. :)
